#!/usr/bin/env bash
#PBS -A lp_sys
#PBS -l nodes=1:ppn=36
#PBS -l walltime=00:05:00
#PBS -joe

cd $PBS_O_WORKDIR

module load intel
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/apps/leuven/skylake/2018a/software/icc/2018.1.163-GCC-6.4.0-2.28/tbb/lib/intel64/gcc4.7/"

child_prob="0.95"
max_depth="38"
seed="495845"

# show runtime parameters
echo "# child_prob = ${child_prob}"
echo "# max_depth = ${max_depth}"
echo "# seed = ${seed}"

for run_nr in 1 2 3
do
    echo "run nr. = ${run_nr}"
    ./build/src/tree_test.exe \
        "${child_prob}" "${max_depth}" "${seed}"
done
