CXX = g++
CXXFLAGS = -O4 -march=skylake-avx512

all: aos_soa_foss.exe

aos_soa_foss.exe: aos_soa.o
	$(CXX) $(CXXFLAGS) -o $@ $<

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	$(RM) $(wildcard *.o) aos_soa_foss.exe
