CC = icc
CFLAGS = -O2 -g
OMP = -openmp
LIBS =

APPS = allocation_serial.exe allocation_omp.exe

all: $(APPS)

%_serial.exe: %.c
	$(CC) $(CFLAGS) -diag-disable 3180 -o $@ $< $(LIBS)

%_omp.exe: %.c
	$(CC) $(CFLAGS) $(OMP) -o $@ $< $(LIBS)

clean:
	rm -f $(APPS) *.o
