#!/bin/bash -l
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -j oe

module load Java/1.7.0_51

cd $PBS_O_WORKDIR

nr_threads=20

pi_output=`java -classpath "pi_computer.jar:pi_app.jar" \
                PiDriver ${nr_threads} ${nr_threads} ${delta_x}`

pi=`echo ${pi_output} | cut -f 2 -d '=' | tr -d [:blank:]`
printf "%.2e\t%.15f\t%02d\t%s\n" ${delta_x} ${pi} ${WORKER_RANK} \
                                 `hostname`
