#!/bin/bash -l
#PBS -l nodes=1:ppn=20:ivybridge
#PBS -l walltime=00:15:00
#PBS -l qos=debugging
#PBS -j oe

cd $PBS_O_WORKDIR
source switch_to_2016a
module load intel/2016a

APPL=cache_hierarchy
PROF_DIR=./profiles

# build with -O2, time
rm -f ${APPL}
icc -O3 -xHOST -o ${APPL} ${APPL}.c
echo '-O3 run'
time ./${APPL} > cache_hierarchy_O3.txt

# build with instrumentation for FDO, time, but disgard output
rm -f ${APPL}
mkdir -p ${PROF_DIR}
icc -prof-gen -prof-dir=${PROF_DIR} -o ${APPL} ${APPL}.c
echo 'instrumented run'
time ./${APPL} > /dev/null

# build using profile information and time
rm -f ${APPL}
icc -prof-use -prof-dir=${PROF_DIR} -ipo -o ${APPL} ${APPL}.c
rm -f ${APPL}.gcda
echo 'FDO run'
time ./${APPL} > cache_hierarchy_O3_FDO.txt
