#!/bin/bash -l
#PBS -l nodes=3:ppn=20
#PBS -l walltime=00:30:00

cd $PBS_O_WORKDIR

scheduler_node=$(head -1 $PBS_NODEFILE)
worker_nodes=$(uniq $PBS_NODEFILE)
worker_launcher="$(pwd)/launch_worker.sh"

echo 'launching scheduler'
./launch_scheduler.sh

echo 'waitling till scheduler launched...'
sleep 15

echo 'starting workers...'
for worker in $worker_nodes;
do
    echo "launching worker on ${worker}"
    ssh $worker $worker_launcher "${scheduler_node}:8786" &
done

echo 'waiting for workers to start and connect'
sleep 15

source "$VSC_DATA/miniconda3/setenv.sh"
source activate science

which python

echo 'starting computation'
time python dask_distr_test.py --scheduler $scheduler_node \
                               --scheduler_port 8786
